[package]
name = "pyduckling"  # Replace with your actual package name
version = "0.1.0"
edition = "2018"

[dependencies]
pendulum = "0.3.1"  # Replace with the appropriate version
pyo3 = { version = "0.15", features = ["extension-module"] }
